# https://code.visualstudio.com/api/references/extension-manifest
# https://json.schemastore.org/package
version: 0.0.0
name: "@danielbayley/svgo-plugin-chameleon"
description: Simple SVGO plugin to change fill and stroke attribute colors.
keywords:
- svg
- svgo
- optimize
- optimise
- plugin
- colors
- colours

homepage: https://github.com/danielbayley/svgo-plugin-chameleon#readme
repository: https://github.com/danielbayley/svgo-plugin-chameleon
bugs: https://github.com/danielbayley/svgo-plugin-chameleon/issues #/discussions/categories/q-a
  #url:
  #email: &email daniel.bayley@me.com

author: #Daniel Bayley <daniel.bayley@me.com> (https://github.com/danielbayley)
  name: Daniel Bayley
  email: daniel.bayley@me.com #*email
  url: danielbayley.dev

license: MIT
funding: https://github.com/sponsors/danielbayley
  #type: github
  #url:
#- type: custom
  #url: https://paypal.com/paypalme/danieljbayley #https://danielbayley.dev/sponsor #/donate

type: module
exports: &index index.js #./ #&esm
  #import: &index index.js #.mjs
  #require: index.cjs #.js
#files: [*index, TODO]
#- *index
#types: index.d.ts
engines:
  node: ">=18"
  vscode: ^1.29.0

packageManager: pnpm@8.9.0
devDependencies:
  "@commitlint/cli": ^17.7.2
  #"@danielbayley/svgo-plugin-import-style-element": ^T0D0
  #"@resvg/resvg-js": ^2.4.1
  autoprefixer: ^10.4.16
  capture-website-cli: ^2.3.0
  chokidar-cli: ^3.0.0
  commitgpt: ^2.0.0 #4: ^1.2.0
  #jest: ^29.7.0
  #pageres-cli: ^6.0.1
  postcss: ^8.4.31
  postcss-cli: ^10.1.0
  #sharp-cli: ^2.1.0
  #sharp: ^0.32.6
  #svg-render: ^1.2.0
  svg-term-cli: ^2.1.1
  #svgexport: ^0.4.2
  yamljs: ^0.3.0

#dependencies:
  #read-pkg: ^8.1.0 #-up: ^10.1.0

peerDependencies: #optionalDependencies: TODO
  svgo: ^3.0.2

#postcss:
  #TODO: TODO

#config:
  #TODO: TODO

#publishConfig:
  #TODO: TODO

scripts:
  #docs: TODO
  build: pnpm /^build.+/
  #build.svg: svgo --TODO #postcss --TODO #.illustration:
  #svgexport *.svg social-preview.png 10x -32:0:128:64
  build.social-preview: capture-website *.svg --no-block-ads --delay 8 --height 640 --output social-preview.png --overwrite
    #--disable-animations FIXME
    #open $npm_package_repository/settings

  #build.svg-term: svg-term TODO
  build.manifest: yaml2json package.y*ml --save --pretty #--indentation ${TABSIZE:-2} #${=TABSIZE:+--indentation $TABSIZE}

  #pretest: pnpm prepare
  test: node test/*.js #jest TODO

  prepare: pnpm build #.manifest
  #prepublishOnly: TODO
  release: pnpm publish

  watch: pnpm /^watch.+/ #develop:
  watch.social-preview: chokidar *.svg --command 'pnpm build.social-preview' #--overwrite'
  watch.manifest: pnpm build.manifest --watch

  #clean: TODO package.json


# TODO
# https://github.com/svg/svgo/blob/main/plugins-api.md#definitive-guide-about-building-svgo-plugins
# https://github.com/uranetz/setCurrentColor
